version: 2

project_name: filebrowser

env:
  - GO111MODULE=on

before:
  hooks:
    - go install github.com/rakyll/statik@latest
    - go install github.com/abice/go-enum@latest
    - sh -c "cd frontend && bun install && bun run build"
    - sh -c "export PATH=$(go env GOPATH)/bin:$PATH; go generate ./..."

builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/filebrowser/filebrowser/v2/version.Version={{ .Version }} -X github.com/filebrowser/filebrowser/v2/version.CommitSHA={{ .ShortCommit }}
    tags:
      - netgo
      - osusergo
      - static
    main: main.go
    binary: filebrowser
    goos:
      - linux
    goarch:
      - riscv64
      - arm64
      - amd64
    goriscv64:
      - rva22u64
    goarm64:
      - v8.0
    goamd64:
      - v1

archives:
  - id: archive-disabled
    formats: none

nfpms:
  - id: default
    package_name: filebrowser
    file_name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    vendor: "Filebrowser Maintainers"
    homepage: "https://filebrowser.org"
    maintainer: "FileBrowser Robot <robot@filebrowser.org>"
    description: "Web File Browser"
    license: "Apache 2.0"
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: ./filebrowser.service
        dst: /usr/lib/systemd/system/filebrowser.service
        file_info:
          mode: 0644
          owner: root
          group: root
    scripts:
      preinstall: ./nfpms/preinst
      postinstall: ./nfpms/postinst
      preremove: ./nfpms/prerm
      postremove: ./nfpms/postrm
