// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package fbhttp

import (
	"database/sql/driver"
	"errors"
	"fmt"
	"strings"
)

const (
	// PreviewSizeThumb is a PreviewSize of type Thumb.
	PreviewSizeThumb PreviewSize = iota
	// PreviewSizeBig is a PreviewSize of type Big.
	PreviewSizeBig
)

var ErrInvalidPreviewSize = fmt.Errorf("not a valid PreviewSize, try [%s]", strings.Join(_PreviewSizeNames, ", "))

const _PreviewSizeName = "thumbbig"

var _PreviewSizeNames = []string{
	_PreviewSizeName[0:5],
	_PreviewSizeName[5:8],
}

// PreviewSizeNames returns a list of possible string values of PreviewSize.
func PreviewSizeNames() []string {
	tmp := make([]string, len(_PreviewSizeNames))
	copy(tmp, _PreviewSizeNames)
	return tmp
}

var _PreviewSizeMap = map[PreviewSize]string{
	PreviewSizeThumb: _PreviewSizeName[0:5],
	PreviewSizeBig:   _PreviewSizeName[5:8],
}

// String implements the Stringer interface.
func (x PreviewSize) String() string {
	if str, ok := _PreviewSizeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("PreviewSize(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PreviewSize) IsValid() bool {
	_, ok := _PreviewSizeMap[x]
	return ok
}

var _PreviewSizeValue = map[string]PreviewSize{
	_PreviewSizeName[0:5]: PreviewSizeThumb,
	_PreviewSizeName[5:8]: PreviewSizeBig,
}

// ParsePreviewSize attempts to convert a string to a PreviewSize.
func ParsePreviewSize(name string) (PreviewSize, error) {
	if x, ok := _PreviewSizeValue[name]; ok {
		return x, nil
	}
	return PreviewSize(0), fmt.Errorf("%s is %w", name, ErrInvalidPreviewSize)
}

// MarshalText implements the text marshaller method.
func (x PreviewSize) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PreviewSize) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParsePreviewSize(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PreviewSize) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

var errPreviewSizeNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *PreviewSize) Scan(value interface{}) (err error) {
	if value == nil {
		*x = PreviewSize(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = PreviewSize(v)
	case string:
		*x, err = ParsePreviewSize(v)
	case []byte:
		*x, err = ParsePreviewSize(string(v))
	case PreviewSize:
		*x = v
	case int:
		*x = PreviewSize(v)
	case *PreviewSize:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = *v
	case uint:
		*x = PreviewSize(v)
	case uint64:
		*x = PreviewSize(v)
	case *int:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = PreviewSize(*v)
	case *int64:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = PreviewSize(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = PreviewSize(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = PreviewSize(*v)
	case *uint:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = PreviewSize(*v)
	case *uint64:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x = PreviewSize(*v)
	case *string:
		if v == nil {
			return errPreviewSizeNilPtr
		}
		*x, err = ParsePreviewSize(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x PreviewSize) Value() (driver.Value, error) {
	return x.String(), nil
}
