#!/bin/sh
set -e

CONFIG_DIR="/etc/filebrowser"
CONFIG_FILE="$CONFIG_DIR/filebrowser.json"
SERVICE_USER="filebrowser"
SERVICE_GROUP="filebrowser"

# Function: Determines if it is an upgrade operation
is_upgrade() {
    # RPM Upgrade: $1 = 2
    if [ "$1" = "2" ]; then return 0; fi
    # Debian upgrade: $1 = configure and $2 is not empty
    if [ "$1" = "configure" ] && [ -n "$2" ]; then return 0; fi
    return 1
}

# Perform the following configuration for any installation or upgrade.
if [ "$1" = "configure" ] || [ "$1" = "1" ] || [ "$1" = "2" ]; then

    # 1. Create a default configuration file (only if it does not exist)
    if [ ! -f "$CONFIG_FILE" ]; then
        cat >"$CONFIG_FILE" <<EOF
{
  "address": "0.0.0.0",
  "port": 59230,
  "database": "$CONFIG_DIR/filebrowser.db",
  "root": "/mnt/filebrowser"
}
EOF
        chown $SERVICE_USER:$SERVICE_GROUP "$CONFIG_FILE"
    fi

    systemctl daemon-reload
    systemctl enable filebrowser.service
    if is_upgrade "$1" "$2"; then
        # --- Upgrade Scene ---
        systemctl restart filebrowser.service || true
    fi
fi

exit 0
